### PR TITLE
avoid returning outside function

### PR DESCRIPTION
**Pull request by ysangkok**
Babel reports a SyntaxError when encountering this.

### CODE REVIEW

**Comment by davisjam** [comment]
If I understand this correctly, you're suggesting that mkdirp exit 1 (an error code) when the user asks for help. If so, this is inconsistent with typical UNIX behavior. If the user asks for help, the exit code should be 0. If he uses mkdirp incorrectly, on the other hand, the exit code should be 1.

$ mkdir --help >/dev/null 2>&1; echo $? 
0
$ ls --help >/dev/null 2>&1; echo $?
0

**Comment by ysangkok** [comment]
@davisjam I fixed that issue. It is of course convention. My logic went like this: Since no batch usage of this program should use the help flag, it is best if the program in a script usage provokes an error, since a legitimate ask for help will not suffer from the exit code 1. But I can understand your logic too.

**Comment by davisjam** [comment]
This PR now looks good to me.

**Comment by ysangkok** [comment]
Closing since it clobbers my PR listing page and I don't think anybody cares about it.

**Pull request closed without merging**
