### PR TITLE
include only necessary files in npm package

### PR DESCRIPTION
**Pull request by deepsweet**
```
$ tree node_modules/mkdirp -I node_modules

node_modules/mkdirp
├── bin/
│   ├── cmd.js*
│   └── usage.txt
├── examples/
│   └── pow.js
├── test/
│   ├── chmod.js
│   ├── clobber.js
│   ├── mkdirp.js
│   ├── opts_fs.js
│   ├── opts_fs_sync.js
│   ├── perm.js
│   ├── perm_sync.js
│   ├── race.js
│   ├── rel.js
│   ├── return.js
│   ├── return_sync.js
│   ├── root.js
│   ├── sync.js
│   ├── umask.js
│   └── umask_sync.js
├── .travis.yml
├── LICENSE
├── index.js
├── package.json
└── readme.markdown
```

Loading unnecessary files is one of the reasons `npm install`s take so darn long. Anton Rudeshko very well put it in [his article](http://www.rudeshko.com/web/2014/05/13/help-people-consume-your-npm-packages.html):

> Speaking in terms of object-oriented design, your npm package should be [highly cohesive](https://en.wikipedia.org/wiki/Cohesion_%28computer_science%29) and [loosely coupled](https://en.wikipedia.org/wiki/Loose_coupling). Your package should do only one thing and do it well.

Corey Butler also wrote [a nice article](https://medium.com/@goldglovecb/npm-needs-a-personal-trainer-537e0f8859c6) about why it's important to minimize module footprints, including test suite:

> In the rare situation a developer actually wants to run your test suite on their own local computer, they'll likely clone or fork it.

Also see [NPM docs](https://docs.npmjs.com/files/package.json#files) for details about `files` field in `package.json`.

### CODE REVIEW

**Comment by ljharb** [comment]
All files are necessary - as I explained in https://github.com/substack/tape/pull/260.

**Comment by stefanpenner** [comment]
@ljharb this does come at a fairly hefty cost. Especially given how IO heavy npm currently is. Are you interested in reopening discussion on what you explained here:  substack/tape#260. ?

**Comment by yoshuawuyts** [comment]
> Loading unnecessary files is one of the reasons npm installs take so darn long

Yeah nah, not really. You're downloading a tarball from the registry, not individual files. The files in this repo are minuscule, so in terms of size they're negligible compared to, say, `babel`, `webpack`, native addons or whatever other big popular things people toss into their projects nowadays.

Even creating file descriptors is not an issue given that `libuv` provides us with non-blocking handles for IO; it falls in the water compared to roundtrip times.

I think there are only two realistic solutions to solve this problem. Either `npm` and `node` recognize the module loader has a problem regarding symlinks, and find a way to solve module resolution so we can `symlink` packages from a local registry (quite similar to what `pnpm` does). Or we find a solution in userland, like `ipfs`' Content Addressable npm cache that can be run locally, acting as a proxy and forcing a local lookup in the cache before forwarding requests upstream.

The CA npm cache analogy could even be taken further, and prune `test/` and `docs/` repos from being copied over out of the box. Idk, there's stuff possible that doesn't require pinging every single project in a dependency tree and having lengthy discussions. Instead of changing the world to fit our tools, I suggest we change our tools to do a better job at interfacing with the world.

I understand your concern about slow install times, and share your frustration. But removing a few bytes from this repo accomplishes nothing - it only frustrates the people that depend on the documentation, tests and examples to get work done. Thanks!

**Comment by stefanpenner** [comment]
@yoshuawuyts its worth pointing out that, although network IO may affect some. A surprisingly substantial amount of time during an `npm install` is spent merely  handle the large number of discrete files (from tgz -> <project_path>/node_modules)

I can accept some maintainers don't believe it is a priority or even as issue.

I also accept that some projects, like babel, ember-cli, npm, bower are absolutely larger offenders, and must/are/will be addressed.  But it is worth pointing out, even with npm v3, some of those projects end up with 18 different versions of mkdirp in their dependency graph. 

Again, although this projects impact alone is tiny, this is a bit of a "death by a thousand papercuts" problem. If everyone cleans up their small bit of the npm verse, everyone benefits.

**Comment by yoshuawuyts** [comment]
> Again, although this projects impact alone is tiny, this is a bit of a "death by a thousand papercuts" problem. If everyone cleans up their small bit of the npm verse, everyone benefits.

Yeah, I understand where you're coming from. It's just that I don't agree that removing `example` / `test` files from the repositories themselves is worth the tradeoff of slightly faster downloads.

See so when I was living in Australia earlier this year I had a 4 hour commute every single day. 2 hours up to Sydney, 2 hours down from Sydney. That was 4 productive hours a day in a dead zone. When arriving at home, there would be internet - most of the time. But it wasn't fast, nor reliable. Now, the only reason I was able to do any type of development during that time is because `npm` worked offline. And I'm not just talking installs. I'm talking documentation. If I couldn't figure out how a package worked I'd have the docs and examples on my machine already.

I don't think this bad internet is an edge case. The majority of the world isn't on premium internet connections. People travel, even in wealthy areas coverage can be flaky. I think it's important for `npm` to work _anywhere_.

I'm not trying to dismiss your point though. I agree that install times are problematic. I can't deny that I've noticed IO going up to a 100 when installing things, so yeah that should be addressed. But I feel there should other ways of reaching that, that are not the omission of reference material being uploaded to `npm`.

I hope this gives you a better idea where I'm coming from. Thanks!

**Comment by stefanpenner** [comment]
@yoshuawuyts very reasonable. It truly sounds like we want a hybrid (it has come up on the @npminc issue tracker before), potentially a way to opt in or out of "extra material".

**Comment by stefanpenner** [comment]
Given that we do not have this currently, it seems reasonable to:

* make sure no accidentally included (different on a per project/maintainer basis) 
* remind our friends at npm, to consider this more formally when it works based on their triaging (I can imagine they have lots of stuff on there plate already).

**Comment by stefanpenner** [comment]
Honestly though, we may also want to push hard on mkdirp being part of the stdlib... but that is another problem for another day.

**Comment by Turbo87** [comment]
> It truly sounds like we want a hybrid (it has come up on the @npminc issue tracker before), potentially a way to opt in or out of "extra material".

I kinda feel reminded of the Java world where you basically create several artifacts per project for the bytecode, the actual Java sources, the tests, the javadoc, ... 😉

**Comment by Turbo87** [comment]
> Honestly though, in this exact scenario, we may also want to push hard on mkdirp being part of the stdlib...

FWIW https://github.com/jprichardson/node-fs-extra includes a `mkdirp` function too

**Pull request closed without merging**
