### PR TITLE
Update minimist dependency and .npmignore

### PR DESCRIPTION
**Pull request by lorenzleutgeb**
The dependency on minimist was out of date.

Resolve #42.

Please `npm publish` in case you accept this PR.

### CODE REVIEW

**Comment by stefanpenner** [comment]
@substack friendly reminder

**Comment by flowlo** [comment]
Updated this ... after more than a year :astonished:

**Comment by flowlo** [comment]
`minimist` is now 1.2.0, ping @substack

**Comment by lorenzleutgeb** [comment]
Closing this PR out of frustration.

**Pull request closed without merging**
